#ifndef VE_PROD_ID_PV_INVERTERS_H
#define VE_PROD_ID_PV_INVERTERS_H

#ifndef VE_PROD_ID_PV_INVERTER_FRONIUS
#define VE_PROD_ID_PV_INVERTER_FRONIUS 0xA142
#endif

#ifndef VE_PROD_ID_PV_INVERTER_SMA
#define VE_PROD_ID_PV_INVERTER_SMA 0xA143
#endif

#ifndef VE_PROD_ID_PV_INVERTER_SUNSPEC
#define VE_PROD_ID_PV_INVERTER_SUNSPEC 0xA144
#endif

#ifndef VE_PROD_ID_PV_INVERTER_ABB
#define VE_PROD_ID_PV_INVERTER_ABB 0xA145
#endif

#endif // VE_PROD_ID_PV_INVERTERS_H
